# Generated by Django 3.2.7 on 2021-09-23 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answercrquestion',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_crq', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answersrquestion',
            name='student',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='answer_srq', to=settings.AUTH_USER_MODEL),
        ),
    ]
