# Generated by Django 3.2.7 on 2021-09-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_auto_20210923_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradedassignment',
            name='CRQs_grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gradedassignment',
            name='SRQs_grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
