# Generated by Django 3.2.7 on 2021-09-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_auto_20210923_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradedassignment',
            name='CRQs_grade',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='gradedassignment',
            name='SRQs_grade',
            field=models.FloatField(default=0),
        ),
    ]
